[book]
title = "BOXES"
author = "Roberto Alsina"
description = "The whole lifecycle of a project."

[build]
build-dir = "public"
create-missing = true

[output.html]
additional-css = ["custom.css"]

[output.html.search]
limit-results = 15
